name: BentoBoxBedrockCompanion
version: ${version}
main: dev.qwe664.bbc.BentoBoxBedrockCompanion
api-version: "1.21"

author: qwe664
description: Companion plugin for BentoBox to improve the Bedrock player experience.

depend:
  - BentoBox
  - floodgate
commands:
  bbc:
    description: Open BentoBox Bedrock Companion menu
    usage: /bbc
